### PR TITLE
More fitting algorithms and type hints

### PR DESCRIPTION
**Pull request by nup002**
This pull request extends the functionality of the `circle-fits` package by implementing 6 additional circle fitting algorithms based on [MATLAB implementations](https://people.cas.uab.edu/~mosya/cl/MATLABcircle.html) by Nikolai Chernov.
```
- riemannSWFLa()  : Riemann circle fit, SWFL version A
- lm()            : Levenberg-Marquardt in the full (a,b,R) parameter space
- prattSVD()      : Algebraic circle fit by V. Pratt
- taubinSVD()     : Algebraic circle fit by G. Taubin
- hyperSVD()      : Algebraic circle fit with "hyperaccuracy"
- kmh()           : Consistent circle fit by A. Kukush, I. Markovsky, S. Van Huffel
```

Other enhancements:
 - Thorough type hinting of all functions
 - Detailed docstrings

Changes:
 - `hyper_fit()` has been renamed to `hyperLSQ()` to homogenize algorithm names
 - `least_squares_circle()` has been renamed to `standardLSQ()` to homogenize algorithm names
 - Calling `hyper_fit()` or `least_squares_circle()` will only raise a DeprecationWarning in order to not break backwards compatibility.
 
The new algorithms have been added to the demo notebook `demo.ipynb` and the unittests `test.py`.

### CODE REVIEW

**Comment by nup002** [comment]
If nothing happens here @AlliedToasters I'll release `circle-fits2`.

**Comment by AlliedToasters** [comment]
hey @nup002 , thanks for all your contributions. I'd be happy to merge as long as I can add your contact info to the contributors list - due to the large number of changes, I won't be able to support the expanded codebase alone.. Is that ok with you?

**Comment by AlliedToasters** [comment]
@nup002 please fetch the latest README.md and add an email to the Contact section - once you do it, I can build and publish a new release with your changes!

**Comment by nup002** [comment]
Hi AlliedToaster, I am very happy to see you here! I was hoping I would not have to release a new circle-fit package.
I will add my contact information to the readme.

**Review by AlliedToasters — APPROVED** [review]

**Comment by AlliedToasters** [comment]
@nup002 I am traveling today - once I am able to build and test the library, I will publish 0.2.0 to pypi! Thanks again for your contributions and I'm happy to have you here :)

**Comment by nup002** [comment]
@AlliedToasters Thank you for the invitation to collaborate on this repository! I am adding a few more commits, and then it should be ready for version 0.2.0. 

Note that I have changed the build system from setup.py to pyproject.toml with hatchling, just like it is explained in the official documentation on packaging: https://packaging.python.org/en/latest/tutorials/packaging-projects/

I have also added GitHub Workflows for code style (flake8) and unittests (PyTest). Their results are displayed as badges in the ReadMe together with a few other badges.

I have tested that it builds and installs correctly.

**Comment by AlliedToasters** [comment]
@nup002 v0.2.0 has been released to pypi, thanks a lot for the help!!

**Comment by nup002** [comment]
You're welcome! Just a note on the new linting workflow I added, you can run `flake8` in a command line terminal in the `src` directory before pushing to check if it will pass. I just noticed a lot of linting fix commits

**Pull request merged**
